### ISSUE TITLE
Reading with no -to/-from results in an error

### ISSUE THREAD

**Issue by mstemm** [juttle/juttle-aws-adapter#8]
Reading from aws with no -from or -to results in an error:

```
Error: Cannot read property 'lt' of undefined
Unhandled rejection TypeError: Cannot read property 'lt' of undefined
    at ReadAWS (/Users/mstemm/work/src/juttle-aws-adapter/lib/read.js:27:25)
    at Read (/Users/mstemm/work/src/juttle-aws-adapter/node_modules/juttle/lib/runtime/procs/read.js:28:28)
    at eval (eval at _eval (/Users/mstemm/work/src/juttle-aws-adapter/node_modules/juttle/lib/program.js:36:26), <anonymous>:4:103)
...
```

**Comment by mstemm** [comment]
Fixed in https://github.com/juttle/juttle-aws-adapter/pull/7.
